/* Spruch des Tages: jeden Tag ein anderer Satz unter der Begruessung. Ton: hart und direkt (in der Richtung von David Goggins) und
   philosophisch (stoisch). Alles eigene Formulierungen, keine woertlichen Zitate, deshalb ohne Namen. Die Liste ist fest eingebaut
   (kein Netz noetig); der Satz des Tages ergibt sich aus dem Datum, ist also auf allen Geraeten gleich und wechselt um Mitternacht.
   Wenn alle Saetze einmal dran waren, faengt die Liste wieder von vorn an. Die Reihenfolge ist durchmischt, damit benachbarte Tage
   nichts miteinander zu tun haben. */
(function () {
  const QUOTES = [
    "Stay hard. Dein Komfort hat noch nie ein Ziel erreicht.",
    "Du bist nicht müde, du bist nur bequem geworden.",
    "Der Spiegel lügt nicht. Schau hin und handle.",
    "Wenn du denkst, du kannst nicht mehr, hast du erst vierzig Prozent gegeben.",
    "Niemand kommt, um es für dich zu tun. Steh auf.",
    "Mach es gerade dann, wenn du keine Lust hast.",
    "Schmerz ist der Preis. Zahl ihn und geh weiter.",
    "Die Komfortzone ist ein Gefängnis mit Sofa.",
    "Du wirst nicht stärker, weil es leicht war.",
    "Keine Ausreden, nur Ergebnisse.",
    "Hart wird man nicht im Urlaub, sondern an den Tagen, die wehtun.",
    "Hol dir den Morgen zurück, und der Tag gehört dir.",
    "Was du heute vermeidest, wartet morgen mit Zinsen auf dich.",
    "Dein Kopf gibt auf, lange bevor dein Körper es tut.",
    "Mach den Job, auch wenn dich keiner sieht.",
    "Applaus gibt es später. Arbeit gibt es jetzt.",
    "Hör auf, auf Motivation zu warten. Sie kommt nach dem Anfang.",
    "Du schuldest dir die Version von dir, die du angefangen hast zu sein.",
    "Schwielen entstehen dort, wo es reibt. Geh in die Reibung.",
    "Wer nur macht, was ihm leichtfällt, bleibt, wer er ist.",
    "Dein Widerstand ist dein Trainingsplan.",
    "Jeder Tag ist eine Prüfung. Bestehe sie leise.",
    "Müdigkeit ist ein Gefühl, kein Befehl.",
    "Sei der, der noch arbeitet, wenn alle anderen schon erklärt haben, warum es nicht geht.",
    "Wenn es leicht wäre, wäre es wertlos.",
    "Nimm das Unangenehme zuerst. Danach ist alles Kür.",
    "Du bist härter, als deine Stimme im Kopf behauptet.",
    "Hör auf zu verhandeln mit dir selbst. Tu es einfach.",
    "Der Weg ist nicht gerecht, aber er gehört dir.",
    "Kein Plan überlebt den Tag, aber ein Wille tut es.",
    "Erfolg ist eine Reihe von Tagen, an denen du nicht aufgegeben hast.",
    "Du musst es nicht mögen. Du musst es nur tun.",
    "Vergleiche dich mit dem Mann von gestern, nicht mit dem von nebenan.",
    "Wer auf Bequemlichkeit trainiert, verliert, wenn es ernst wird.",
    "Mach weiter, wenn niemand klatscht, genau dort wird es wertvoll.",
    "Dein Leben ändert sich an dem Tag, an dem du aufhörst, dich zu entschuldigen.",
    "Du kannst Gründe haben oder Ergebnisse, nicht beides.",
    "Härte ist kein Charakterzug, sondern eine tägliche Entscheidung.",
    "Heute ist der Tag, an dem du beweist, was du gestern versprochen hast.",
    "Wenn der Wecker klingelt, beginnt das Gespräch mit deinem Willen.",
    "Ein weiterer Satz, eine weitere Stunde, ein weiterer Schritt. Mehr braucht es nicht.",
    "Zweifel ist der Lärm, den du aushalten musst.",
    "Wer nicht mehr zurück kann, geht am schnellsten vorwärts.",
    "Keiner macht dich aus Mitleid besser. Mach dich selbst besser.",
    "Niemand ist zu beschäftigt, nur falsch sortiert.",
    "Mach den Tag so schwer, dass der nächste leicht wirkt.",
    "Deine Geschichte ist genau so lang, wie du Rückschläge zulässt.",
    "Lass dich nicht von dem aufhalten, was du fühlst, sondern führe das, was du willst.",
    "Zur Hölle mit der Ausrede. Zur Arbeit.",
    "Wer schweigt und liefert, beeindruckt am meisten.",
    "Der schwierigste Kampf findet vor dem Aufstehen statt.",
    "Gib alles, wenn es zählt, und alles, wenn es nicht zählt.",
    "Mach Schmerz zu deinem Verbündeten, nicht zu deinem Richter.",
    "Du musst keine Superkräfte haben, nur eine Gewohnheit, die nicht nachgibt.",
    "Heute den Wecker schlagen, morgen das Leben.",
    "Hör auf, nach Abkürzungen zu suchen. Es gibt nur die Strecke.",
    "Wenn dein Warum groß genug ist, wird das Wie klein.",
    "Hartnäckigkeit schlägt Talent, wenn Talent faul ist.",
    "Verdiene den Respekt vor dem Spiegel.",
    "Dein Körper tut, was dein Kopf ihm nach der dritten Wiederholung erlaubt.",
    "Gute Tage bauen Selbstvertrauen. Schlechte Tage bauen Charakter.",
    "Du entscheidest, wie dich der Tag formt, nicht umgekehrt.",
    "Fang an, auch wenn dein Atem schon vor dem Start schwer ist.",
    "Sei unangenehm für deine Bequemlichkeit.",
    "Der Beste von morgen ist der, der heute nicht nachgibt.",
    "Nicht alles, was dich fordert, ist ein Hindernis. Manches ist der Weg.",
    "Weißt du, was du kannst? Dann fordere das Doppelte.",
    "Fehler kosten dich nur dann, wenn du sie wiederholst.",
    "Mach dich selbst zu dem, auf den du zählen kannst.",
    "Dein Einsatz muss lauter sein als dein Zweifel.",
    "Alles, was du wirklich willst, liegt hinter dem Punkt, an dem du eigentlich aufhören wolltest.",
    "Was dich nicht stört, wird dich nicht verändern.",
    "Gewöhne dich ans Schwere, dann wird das Leichte Luxus.",
    "Schlaf, wenn du fertig bist. Beweis, dass du fertig bist.",
    "Der Wille wird im Alltag trainiert, nicht im Ausnahmezustand.",
    "Du bist die Summe deiner Taten, nicht deiner Pläne.",
    "Der Moment, in dem du aufhören willst, ist der Moment, in dem es anfängt zu zählen.",
    "Mach heute das, wovor du morgen stolz sein willst.",
    "Aufgeben ist eine Gewohnheit wie jede andere. Stell sie ab.",
    "Sei dir selbst gegenüber so ehrlich, dass es wehtut. Es wirkt.",
    "Dein Gegner sitzt in deinem Kopf. Besiege ihn zuerst.",
    "Verwechsle nicht Beschäftigung mit Fortschritt.",
    "Wer sich nicht selbst antreibt, wird getrieben.",
    "Mach es heute ohne Applaus, damit du morgen keinen brauchst.",
    "Harte Arbeit ist die einzige Abkürzung, die immer ankommt.",
    "Du kannst Angst haben und trotzdem losgehen. Das ist Mut.",
    "Jeder Tag ohne Anstrengung ist ein Tag, den dein Ich von morgen bezahlt.",
    "Lass die Zweifel reden, während du arbeitest.",
    "Dein Limit ist selten dort, wo du es vermutest.",
    "Dein Wille ist ein Muskel. Heute wird trainiert.",
    "Wer verlangt, dass es einfach wird, verlangt, dass er gleich bleibt.",
    "Nicht die Umstände entscheiden, sondern was du daraus machst.",
    "Sei das Beispiel, das du dir selbst wünschst.",
    "Ein hartes Nein zu dir selbst ist ein klares Ja zu deinem Ziel.",
    "Du hältst mehr aus, als du glaubst. Beweise es dir.",
    "Mach die Dinge, die dich nervös machen, bis sie dich langweilen.",
    "Heute wird nichts geschenkt. Verdiene jede Minute.",
    "Nicht alles in deiner Macht zu tun, wäre Verrat an dir selbst.",
    "Nur was in deiner Macht liegt, verdient deine Sorge. Alles andere ist Wetter.",
    "Der Weg ist das Hindernis, und das Hindernis ist der Weg.",
    "Du kannst nicht ändern, was geschieht, aber immer, wie du darauf antwortest.",
    "Das Leben ist kurz. Verschwende es nicht an Dinge, die dich nicht erwarten.",
    "Nicht der Tag ist schlecht, nur dein Urteil darüber.",
    "Wer täglich an das Ende denkt, fängt heute an.",
    "Dein Glück hängt von der Qualität deiner Gedanken ab.",
    "Was dich stört, ist selten die Sache, sondern deine Haltung dazu.",
    "Zeit ist das Einzige, was du nicht zurückkaufen kannst.",
    "Nimm an, was kommt, und mach das Beste daraus.",
    "Betrachte Hindernisse als Material, nicht als Mauer.",
    "Es liegt nie an den Dingen, sondern daran, was wir über sie denken.",
    "Lebe so, dass du den Tag wiederholen würdest.",
    "Du hast Macht über deinen Geist, nicht über die Ereignisse. Erkenne das, und du findest Stärke.",
    "Was zählt, ist nicht, wie lange du lebst, sondern wie du die Tage nutzt.",
    "Nicht das Schwere macht uns Angst, sondern dass wir es nicht versuchen.",
    "Wer sein Warum kennt, erträgt fast jedes Wie.",
    "Ohne Ziel hilft dir auch der beste Wind nicht weiter.",
    "Tu, was du tun musst, und lass das Ergebnis los.",
    "Du wirst zu dem, was du jeden Tag wiederholst. Wiederhole Gutes.",
    "Wir leiden öfter in der Vorstellung als in der Wirklichkeit.",
    "Andere zu schlagen macht stark, sich selbst zu schlagen macht frei.",
    "Hadere nicht mit dem, was geschieht. Entscheide, was du daraus machst.",
    "Ein klarer Anfang spart dir die halbe Arbeit.",
    "Tapferkeit ist, trotz der Angst das Richtige zu tun.",
    "Sei ein Fels, an dem sich die Wellen brechen, und bleib ruhig.",
    "Wer nach außen blickt, träumt. Wer nach innen blickt, erwacht.",
    "Man wird nicht klug durch Warten, sondern durch Tun und Nachdenken.",
    "Das Glück begleitet nicht den Bequemen, sondern den Bereiten.",
    "Heute lebst du nur einmal. Mach es zählbar.",
    "Die größte Freiheit ist die Disziplin, die du dir selbst gibst.",
    "Erinnere dich, dass du sterblich bist, und lebe wie jemand, der Zeit hat und trotzdem keine verschwendet.",
    "Du kannst nicht fliehen vor dem, was du bist. Also werde, wer du sein willst.",
    "Gelassenheit ist keine Schwäche, sondern geübte Stärke.",
    "Das Hindernis nützt dir, wenn du es nutzt.",
    "Aus Mühe wächst Gleichmut, aus Gleichmut wächst Kraft.",
    "Wer sich selbst beherrscht, braucht nichts zu fürchten.",
    "Die Wahrheit über dich siehst du an dem, was du tust, wenn niemand hinsieht.",
    "Wer alles hat und nichts tut, hat wenig. Wer wenig hat und viel tut, hat alles.",
    "Mut ist, die Schritte zu gehen, bevor der Weg klar ist.",
    "Die Zeit verrinnt nicht, du verschwendest sie nur.",
    "Es ist nicht wenig Zeit, die wir haben, sondern viel, die wir nicht nutzen.",
    "Wer gut lebt, übt täglich das Sterben und fürchtet sich nicht mehr vor dem Morgen.",
    "Wo Angst ist, ist meist ein Grund, hinzugehen.",
    "Selbsterkenntnis beginnt mit dem Mut, sich selbst unbequem zu sein.",
    "Das Leben wird nicht leichter, du wirst stärker. Das ist der Unterschied.",
    "Ändere deine Gedanken, und du änderst deine Welt.",
    "Die beste Rache ist, nicht so zu werden wie der, der dich verletzt hat.",
    "Nicht der Schmerz zerbricht dich, sondern die Geschichte, die du ihm gibst.",
    "Prüfe dein Leben, aber bleib dabei in Bewegung.",
    "Wer immer nur Zuschauer bleibt, gewinnt nichts außer Meinungen.",
    "Sei dankbar für das Schwere, es zeigt dir, wo du wachsen kannst.",
    "Wer jeden Morgen neu beginnt, kann nie zu spät sein.",
    "Was uns im Weg steht, ist oft der Beginn des Weges.",
    "Alles, was du brauchst, liegt in dem, was du heute tust.",
    "Die Unruhe in dir ist ein Kompass. Folge dem, was dich ruft.",
    "Wissen allein bewegt nichts. Erst das Tun macht daraus Leben.",
    "Der Mut, schlecht anzufangen, ist der Grund für jedes gute Ende.",
    "Wer sich dem Lauf der Dinge stellt, kann ihn mitgestalten.",
    "Deine Gedanken färben deine Seele, achte darauf, was du denkst.",
    "Nichts ist ewig. Handle, solange du es kannst.",
    "Wer dem Leben dient, indem er sich selbst überwindet, wird frei.",
    "Besitze deinen Tag, bevor er dich besitzt.",
    "Weisheit ist, zu wissen, was in deiner Hand liegt, und es dann auch zu tun.",
    "Nimm die Dinge, wie sie sind, und forme, was du formen kannst.",
    "Es ist nie zu spät, der zu werden, der du sein könntest.",
    "Auf einen langen Weg gehört ein erster Schritt, nicht ein perfekter.",
    "Wer den Sturm nicht fürchtet, braucht auch keine Windstille.",
    "Das Ziel ist das, was dich ausrichtet. Der Weg ist das, was dich formt.",
    "Zufriedenheit liegt nicht im Haben, sondern im Brauchen von weniger.",
    "Nichts verändert den Menschen so sehr wie das, was er täglich übt.",
    "Gelassen bleibt, wer weiß, dass er nur sich selbst regieren kann."
  ];
  const N = QUOTES.length;
  // Tag der Zaehlung aus dem lokalen Datum (nicht aus der Uhrzeit), damit der Satz erst um Mitternacht wechselt; mal einem zur Listenlaenge
  // teilerfremden Schritt (ab 7) mischt die Reihenfolge, ohne dass sich ein Satz vor dem Listenende wiederholt.
  window.dailyQuote = function (date) {
    const d = date || new Date();
    const day = Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / 86400000);
    const gcd = (a, b) => (b ? gcd(b, a % b) : a);
    let step = 7;
    while (gcd(N, step) !== 1) step += 2;
    return QUOTES[(day * step) % N];
  };
  window.dailyQuoteCount = N;
})();
