/* Spruch des Tages: jeden Tag ein anderer Satz unter der Begruessung. Die Liste ist fest eingebaut (kein Netz noetig); der Satz
   des Tages ergibt sich aus dem Datum, ist also auf allen Geraeten gleich und wechselt um Mitternacht. Wenn alle Saetze einmal dran waren, faengt
   die Liste wieder von vorn an. Die Reihenfolge ist durchmischt, damit benachbarte Tage nichts miteinander zu tun haben. */
(function () {
  const QUOTES = [
    "Fang an, bevor du bereit bist. Bereit wirst du unterwegs.",
    "Kleine Schritte, jeden Tag, schlagen den großen Plan, der nie startet.",
    "Heute zählt mehr als jemals.",
    "Du musst nicht schnell sein. Du musst nur weitermachen.",
    "Aus einem schlechten Video wird das zweite. Aus keinem wird nichts.",
    "Disziplin ist die Brücke zwischen Ziel und Ergebnis.",
    "Wer täglich ein Prozent besser wird, erkennt sich in einem Jahr nicht wieder.",
    "Fokus ist, Nein zu sagen zu allem, was nur gut klingt.",
    "Der beste Zeitpunkt war gestern. Der zweitbeste ist jetzt.",
    "Fortschritt ist leise. Er sieht aus wie ein ganz normaler Tag.",
    "Mach es unperfekt, aber mach es.",
    "Was du heute baust, trägt dich im nächsten Jahr.",
    "Zweifel gehören dazu. Du darfst trotzdem losgehen.",
    "Ein Stein nach dem anderen, so entsteht die ganze Sammlung.",
    "Erst die schwerste Aufgabe, dann wird der Rest leicht.",
    "Du bist näher dran, als es sich anfühlt.",
    "Konstanz schlägt Motivation, jedes Mal.",
    "Jeder Upload ist ein Beweis, dass du dranbleibst.",
    "Nicht perfekt planen, sondern ehrlich anfangen.",
    "Ein ruhiger Kopf trifft die besseren Entscheidungen.",
    "Müde bist du am Ende des Tages. Am Anfang bist du nur noch nicht warm.",
    "Gewohnheiten entscheiden, wer du in einem Jahr bist.",
    "Wer wartet, bis alles passt, wartet für immer.",
    "Das Ziel wird nicht kleiner, wenn du es verschiebst.",
    "Heute nur eine Sache richtig gut machen.",
    "Lernen fühlt sich anfangs immer wie Stolpern an.",
    "Dein Tempo ist deins. Wichtig ist die Richtung.",
    "Jede Zahl, die du heute steigerst, war gestern noch eine Idee.",
    "Mut ist, trotzdem auf Veröffentlichen zu klicken.",
    "Ein guter Tag beginnt mit einer klaren ersten Aufgabe.",
    "Wer sein Handwerk liebt, wird jeden Tag ein Stück besser.",
    "Aufgeben ist keine Option, Pausen sind es schon.",
    "Du musst nicht alles heute schaffen, nur das Wichtige.",
    "Große Kanäle haben mit dem ersten Video begonnen.",
    "Kritik an der Arbeit ist kein Urteil über dich.",
    "Mehr Handeln, weniger Grübeln.",
    "Ein Plan ohne ersten Schritt ist nur ein Wunsch.",
    "Ruhe ist Teil der Leistung.",
    "Du hast schon Schwereres geschafft als das hier.",
    "Wer heute übt, spart morgen die Ausreden.",
    "Mach die Dinge so, dass dein zukünftiges Ich nickt.",
    "Der Weg wird beim Gehen sichtbar.",
    "Erfolg ist die Summe kleiner Wiederholungen.",
    "Frag nicht, ob du Zeit hast. Frag, was dir wichtig ist.",
    "Auch ein langsamer Tag bringt dich nach vorn, wenn du ihn nutzt.",
    "Sei geduldig mit dem Ergebnis und streng mit der Routine.",
    "Qualität entsteht aus Wiederholung, nicht aus Zufall.",
    "Eine Stunde Arbeit am Ziel ist besser als drei Stunden Sorge darüber.",
    "Du baust gerade etwas, das es ohne dich nicht gäbe.",
    "Dranbleiben ist die seltenste Fähigkeit und die wertvollste.",
    "Jeden Tag ein bisschen mutiger als gestern.",
    "Wenn es leicht wäre, hätte es jeder.",
    "Nach dem Chaos kommt die Struktur, wenn du sie baust.",
    "Heute ist ein guter Tag für einen sauberen Start.",
    "Was du misst, verbesserst du. Was du feierst, wiederholst du.",
    "Mach weiter, bevor du es merkst, ist es Gewohnheit.",
    "Ideen sind billig. Umsetzung macht den Unterschied.",
    "Dein Einsatz von heute ist die Freiheit von morgen.",
    "Nicht der perfekte Moment zählt, sondern der nächste Schritt.",
    "Kleine Fortschritte sind trotzdem Fortschritte.",
    "Wer klar weiß, warum, findet fast immer ein Wie.",
    "Räum zuerst den Schreibtisch, dann den Kopf.",
    "Du darfst stolz sein auf das, was du schon aufgebaut hast.",
    "Ausdauer sieht von außen langweilig aus, von innen ist sie Stärke.",
    "Heute wird kein Zufall, heute wird Absicht.",
    "Aus Fehlern wird Erfahrung, wenn du sie ansiehst.",
    "Gute Arbeit braucht Zeit. Gib sie ihr.",
    "Schreib auf, was zählt, und tu es zuerst.",
    "Mehr Mut zur Lücke, mehr Mut zum Anfang.",
    "Dein Ziel braucht dich, nicht deine Ausreden.",
    "Mit jedem Tag wird aus Anstrengung Können.",
    "Die beste Motivation ist ein sichtbarer Fortschritt.",
    "Atme, sortiere, starte.",
    "Wer täglich übt, braucht keine Inspiration mehr.",
    "Ein Nein zu Ablenkung ist ein Ja zu dir.",
    "Ordnung im Kleinen schafft Raum im Großen.",
    "Mach heute den Schritt, den du gestern aufgeschoben hast.",
    "Gelassenheit ist auch Leistung.",
    "Du wächst genau an den Tagen, an denen du keine Lust hast.",
    "Ein Tag ohne Plan frisst dich auf, ein Tag mit Plan trägt dich.",
    "Wiederholung macht aus Wollen ein Können.",
    "Das Beste kommt selten auf Anhieb, aber es kommt.",
    "Wer anfängt, hat schon die halbe Hürde genommen.",
    "Nimm dir weniger vor und schaff es dafür sicher.",
    "Sei freundlich zu dir und streng mit deinem Kalender.",
    "Der erste Entwurf darf schlecht sein, er ist nur der erste.",
    "Dein Durchhalten wirkt, auch wenn es heute keiner sieht.",
    "Konzentration ist ein Muskel. Trainier ihn.",
    "Mach deine Arbeit so gut, dass sie für sich spricht.",
    "Statt mehr Zeit brauchst du oft nur eine klare Entscheidung.",
    "Ruhig bleiben, weitermachen, Ergebnis abwarten.",
    "Wer sein Warum kennt, ertränkt sich nicht im Wie.",
    "Heute ein Häkchen mehr als gestern.",
    "Der Unterschied liegt in den Dingen, die du jeden Tag tust.",
    "Du brauchst keine Genialität, nur Beständigkeit.",
    "Fang klein an und bleib groß im Denken.",
    "Entscheide dich, und der Weg ordnet sich.",
    "Was dich heute fordert, macht dich morgen sicher.",
    "Ein klarer Kopf beginnt mit einem klaren Schreibtisch.",
    "Wenn du nicht weißt, wo du anfangen sollst, fang bei der kleinsten Aufgabe an.",
    "Stolz entsteht, wenn du hältst, was du dir versprochen hast.",
    "Du bist kein Ergebnis von gestern, sondern der Anfang von heute.",
    "Mach Platz für das Wichtige, indem du das Unwichtige lässt.",
    "Auch wenn es klein ist, es zählt.",
    "Dein Kanal wächst mit jedem Tag, an dem du ihn pflegst.",
    "Planen ist gut, tun ist besser.",
    "Zielstrebig heißt nicht hektisch.",
    "Wer lernt, ist der Welt immer einen Schritt voraus.",
    "Eine gute Woche beginnt mit einem guten Montag, aber sie endet nicht dort.",
    "Du darfst müde sein, aber nicht stehen bleiben.",
    "Setz dir ein Ziel, das dich ein bisschen erschreckt.",
    "Deine Zukunft entsteht aus dem, was du heute tust.",
    "Auf die Qualität achten, die Menge ergibt sich.",
    "Lass dich nicht von der Größe des Berges bremsen, nur vom nächsten Schritt leiten.",
    "Schau auf deinen Fortschritt, nicht auf die anderen.",
    "Heute bist du schon weiter, als du denkst.",
    "Mit klaren Prioritäten wird jeder Tag leichter.",
    "Du hast die Wahl: Ausrede oder Anfang.",
    "Beharrlichkeit wirkt langsam und gewinnt trotzdem.",
    "Dein bester Antrieb sitzt in dir, nicht im Kalender.",
    "Genug Pause, dann voller Einsatz.",
    "Ein bewusster Start ist die halbe Miete.",
    "Wer klein beginnt, kann groß werden.",
    "Schwierigkeiten sind Hinweise, keine Verbote.",
    "Gib deiner Idee ein Datum, dann wird sie ein Termin.",
    "Das Ziel vor Augen, den Schritt unter den Füßen.",
    "Jeden Tag ein Stück näher an das Leben, das du willst.",
    "Dein Einsatz heute hat morgen Zinsen.",
    "Kümmere dich um deine Gewohnheiten, die Ergebnisse kümmern sich um sich selbst.",
    "Tu das Wichtige, bevor das Dringende kommt.",
    "Ein Fehler ist ein Lehrer, der nichts kostet, wenn du hinhörst.",
    "Je klarer das Bild, desto leichter der Weg.",
    "Mach dich nicht klein. Mach den nächsten Schritt.",
    "Vom Wollen zum Tun sind es nur ein paar Minuten.",
    "Wer sich selbst vertraut, hält länger durch.",
    "Setz heute den Anfang, den du morgen fortsetzt.",
    "Es reicht, heute ein bisschen besser zu sein als gestern.",
    "Hinter jeder großen Sammlung steckt eine kleine Entscheidung.",
    "Aus Plänen werden Taten, wenn du den ersten Handgriff kennst.",
    "Stärke zeigt sich in der Wiederholung, nicht im einmaligen Ausreißer.",
    "Erledige es, dann hast du den Kopf frei.",
    "Dein Anspruch darf hoch sein, dein erster Schritt klein.",
    "Mach Pause, aber lass das Ziel nicht los.",
    "Echte Arbeit passiert zwischen Idee und Ergebnis.",
    "Der Weg zum Ziel besteht aus unauffälligen Tagen.",
    "Du kannst nicht alles kontrollieren, aber deine Routine schon.",
    "Beginne dort, wo du stehst, mit dem, was du hast.",
    "Jedes Mal, wenn du dranbleibst, wird es ein bisschen leichter.",
    "Gute Tage sind meist gut vorbereitete Tage.",
    "Mach nicht alles auf einmal, mach alles nacheinander.",
    "Wer die Ruhe bewahrt, behält den Überblick.",
    "Eine Entscheidung heute spart eine Woche Zweifel.",
    "Du bringst mehr mit, als du dir zutraust.",
    "Die kleinste Routine ist stärker als die größte Absicht.",
    "Verzettel dich nicht, such dir den einen Hebel.",
    "Wenn du hinfällst, ist das auch Bewegung nach vorn.",
    "Gib dem Tag eine Richtung, dann findet sich der Rest.",
    "Dein nächstes Level wartet hinter der Gewohnheit, die du gerade aufbaust.",
    "Weniger Vergleich, mehr Arbeit an dir selbst.",
    "Das Unfertige von heute ist das Fertige von nächster Woche.",
    "Einmal mehr versucht, ist einmal mehr gelernt.",
    "Bleib neugierig, es hält dich jung im Kopf und im Geschäft.",
    "Mach aus großen Zielen kleine Etappen.",
    "Wer ein Ziel hat, findet Wege, wer keins hat, findet Gründe.",
    "Du wirst es nicht bereuen, heute drangeblieben zu sein.",
    "Sorgfalt im Kleinen zahlt sich im Großen aus.",
    "Heute ist ein neuer Platz auf deiner Liste frei.",
    "Der stärkste Antrieb ist ein Fortschritt, den man sehen kann.",
    "Pack es an, solange die Idee noch warm ist.",
    "Vertrau dem Prozess und liefere jeden Tag.",
    "Nicht jeder Tag muss glänzen, manche müssen nur getan werden.",
    "Klare Ziele, kurze Wege, ruhiger Kopf.",
    "Du hast es in der Hand, heute die richtige Kleinigkeit zu tun.",
    "Wer sich Zeit nimmt, spart sie später.",
    "Dein Fleiß von heute ist der Applaus von morgen.",
    "Beginne den Tag so, wie du ihn beenden möchtest.",
    "Nach jedem Stopp kommt das Weitermachen, sei darauf vorbereitet."
  ];
  const N = QUOTES.length;
  // Tag der Zaehlung aus dem lokalen Datum (nicht aus der Uhrzeit), damit der Satz erst um Mitternacht wechselt; mal einem zur Listenlaenge
  // teilerfremden Schritt (ab 7) mischt die Reihenfolge, ohne dass sich ein Satz vor dem Listenende wiederholt.
  window.dailyQuote = function (date) {
    const d = date || new Date();
    const day = Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / 86400000);
    const gcd = (a, b) => (b ? gcd(b, a % b) : a);
    let step = 7;
    while (gcd(N, step) !== 1) step += 2;
    return QUOTES[(day * step) % N];
  };
  window.dailyQuoteCount = N;
})();
